In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
a = torch.rand(4,10)
a/= torch.linalg.norm(a,dim= 1,keepdim= True)
sim = torch.mm(a,a.T)

In [6]:
np.cov(a)

array([[ 0.03973211,  0.00689481, -0.00234069, -0.01013332],
       [ 0.00689481,  0.01400274, -0.00449387, -0.0010093 ],
       [-0.00234069, -0.00449387,  0.01705343,  0.00095285],
       [-0.01013332, -0.0010093 ,  0.00095285,  0.01565129]])

In [25]:
sim[:2,2:]

# (0--> 2) (1-->4)

tensor([[0.7736, 0.9309],
        [0.7958, 0.9103]])

tensor([[0.7736, 0.7958],
        [0.9309, 0.9103]])

In [7]:
a.sum(dim= 1)

tensor([ 6, 15])